/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FeasibilityStatus = IDL.Variant({
  'good' : IDL.Null,
  'poor' : IDL.Null,
  'moderate' : IDL.Null,
  'excellent' : IDL.Null,
});
export const CreatePredictionRequest = IDL.Record({
  'cloudCover' : IDL.Float64,
  'latitude' : IDL.Float64,
  'predictedWeeklyOutput' : IDL.Float64,
  'precipitation' : IDL.Float64,
  'temperature' : IDL.Float64,
  'azimuthAngle' : IDL.Float64,
  'predictedYearlyOutput' : IDL.Float64,
  'predictedMonthlyOutput' : IDL.Float64,
  'zenithAngle' : IDL.Float64,
  'humidity' : IDL.Float64,
  'longitude' : IDL.Float64,
  'shortwaveRadiation' : IDL.Float64,
  'solarCapacity' : IDL.Float64,
  'feasibilityStatus' : FeasibilityStatus,
  'locationName' : IDL.Text,
  'predictedDailyOutput' : IDL.Float64,
});
export const Timestamp = IDL.Int;
export const Record = IDL.Record({
  'id' : IDL.Text,
  'cloudCover' : IDL.Float64,
  'latitude' : IDL.Float64,
  'predictedWeeklyOutput' : IDL.Float64,
  'precipitation' : IDL.Float64,
  'temperature' : IDL.Float64,
  'azimuthAngle' : IDL.Float64,
  'predictedYearlyOutput' : IDL.Float64,
  'predictedMonthlyOutput' : IDL.Float64,
  'zenithAngle' : IDL.Float64,
  'humidity' : IDL.Float64,
  'longitude' : IDL.Float64,
  'shortwaveRadiation' : IDL.Float64,
  'solarCapacity' : IDL.Float64,
  'timestamp' : Timestamp,
  'feasibilityStatus' : FeasibilityStatus,
  'locationName' : IDL.Text,
  'predictedDailyOutput' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addPrediction' : IDL.Func([CreatePredictionRequest], [], []),
  'clearAllPredictions' : IDL.Func([], [], []),
  'deletePrediction' : IDL.Func([IDL.Text], [], []),
  'getAllPredictions' : IDL.Func([], [IDL.Vec(Record)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FeasibilityStatus = IDL.Variant({
    'good' : IDL.Null,
    'poor' : IDL.Null,
    'moderate' : IDL.Null,
    'excellent' : IDL.Null,
  });
  const CreatePredictionRequest = IDL.Record({
    'cloudCover' : IDL.Float64,
    'latitude' : IDL.Float64,
    'predictedWeeklyOutput' : IDL.Float64,
    'precipitation' : IDL.Float64,
    'temperature' : IDL.Float64,
    'azimuthAngle' : IDL.Float64,
    'predictedYearlyOutput' : IDL.Float64,
    'predictedMonthlyOutput' : IDL.Float64,
    'zenithAngle' : IDL.Float64,
    'humidity' : IDL.Float64,
    'longitude' : IDL.Float64,
    'shortwaveRadiation' : IDL.Float64,
    'solarCapacity' : IDL.Float64,
    'feasibilityStatus' : FeasibilityStatus,
    'locationName' : IDL.Text,
    'predictedDailyOutput' : IDL.Float64,
  });
  const Timestamp = IDL.Int;
  const Record = IDL.Record({
    'id' : IDL.Text,
    'cloudCover' : IDL.Float64,
    'latitude' : IDL.Float64,
    'predictedWeeklyOutput' : IDL.Float64,
    'precipitation' : IDL.Float64,
    'temperature' : IDL.Float64,
    'azimuthAngle' : IDL.Float64,
    'predictedYearlyOutput' : IDL.Float64,
    'predictedMonthlyOutput' : IDL.Float64,
    'zenithAngle' : IDL.Float64,
    'humidity' : IDL.Float64,
    'longitude' : IDL.Float64,
    'shortwaveRadiation' : IDL.Float64,
    'solarCapacity' : IDL.Float64,
    'timestamp' : Timestamp,
    'feasibilityStatus' : FeasibilityStatus,
    'locationName' : IDL.Text,
    'predictedDailyOutput' : IDL.Float64,
  });
  
  return IDL.Service({
    'addPrediction' : IDL.Func([CreatePredictionRequest], [], []),
    'clearAllPredictions' : IDL.Func([], [], []),
    'deletePrediction' : IDL.Func([IDL.Text], [], []),
    'getAllPredictions' : IDL.Func([], [IDL.Vec(Record)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };