/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreatePredictionRequest {
  'cloudCover' : number,
  'latitude' : number,
  'predictedWeeklyOutput' : number,
  'precipitation' : number,
  'temperature' : number,
  'azimuthAngle' : number,
  'predictedYearlyOutput' : number,
  'predictedMonthlyOutput' : number,
  'zenithAngle' : number,
  'humidity' : number,
  'longitude' : number,
  'shortwaveRadiation' : number,
  'solarCapacity' : number,
  'feasibilityStatus' : FeasibilityStatus,
  'locationName' : string,
  'predictedDailyOutput' : number,
}
export type FeasibilityStatus = { 'good' : null } |
  { 'poor' : null } |
  { 'moderate' : null } |
  { 'excellent' : null };
export interface Record {
  'id' : string,
  'cloudCover' : number,
  'latitude' : number,
  'predictedWeeklyOutput' : number,
  'precipitation' : number,
  'temperature' : number,
  'azimuthAngle' : number,
  'predictedYearlyOutput' : number,
  'predictedMonthlyOutput' : number,
  'zenithAngle' : number,
  'humidity' : number,
  'longitude' : number,
  'shortwaveRadiation' : number,
  'solarCapacity' : number,
  'timestamp' : Timestamp,
  'feasibilityStatus' : FeasibilityStatus,
  'locationName' : string,
  'predictedDailyOutput' : number,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'addPrediction' : ActorMethod<[CreatePredictionRequest], undefined>,
  'clearAllPredictions' : ActorMethod<[], undefined>,
  'deletePrediction' : ActorMethod<[string], undefined>,
  'getAllPredictions' : ActorMethod<[], Array<Record>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];