/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface Record_ {
    id: string;
    cloudCover: number;
    latitude: number;
    predictedWeeklyOutput: number;
    precipitation: number;
    temperature: number;
    azimuthAngle: number;
    predictedYearlyOutput: number;
    predictedMonthlyOutput: number;
    zenithAngle: number;
    humidity: number;
    longitude: number;
    shortwaveRadiation: number;
    solarCapacity: number;
    timestamp: Timestamp;
    feasibilityStatus: FeasibilityStatus;
    locationName: string;
    predictedDailyOutput: number;
}
export interface CreatePredictionRequest {
    cloudCover: number;
    latitude: number;
    predictedWeeklyOutput: number;
    precipitation: number;
    temperature: number;
    azimuthAngle: number;
    predictedYearlyOutput: number;
    predictedMonthlyOutput: number;
    zenithAngle: number;
    humidity: number;
    longitude: number;
    shortwaveRadiation: number;
    solarCapacity: number;
    feasibilityStatus: FeasibilityStatus;
    locationName: string;
    predictedDailyOutput: number;
}
export enum FeasibilityStatus {
    good = "good",
    poor = "poor",
    moderate = "moderate",
    excellent = "excellent"
}
export interface backendInterface {
    addPrediction(request: CreatePredictionRequest): Promise<void>;
    clearAllPredictions(): Promise<void>;
    deletePrediction(id: string): Promise<void>;
    getAllPredictions(): Promise<Array<Record_>>;
}
import type { CreatePredictionRequest as _CreatePredictionRequest, FeasibilityStatus as _FeasibilityStatus, Record as _Record, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addPrediction(arg0: CreatePredictionRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPrediction(to_candid_CreatePredictionRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPrediction(to_candid_CreatePredictionRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async clearAllPredictions(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllPredictions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllPredictions();
            return result;
        }
    }
    async deletePrediction(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePrediction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePrediction(arg0);
            return result;
        }
    }
    async getAllPredictions(): Promise<Array<Record_>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPredictions();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPredictions();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_FeasibilityStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeasibilityStatus): FeasibilityStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Record): Record_ {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    cloudCover: number;
    latitude: number;
    predictedWeeklyOutput: number;
    precipitation: number;
    temperature: number;
    azimuthAngle: number;
    predictedYearlyOutput: number;
    predictedMonthlyOutput: number;
    zenithAngle: number;
    humidity: number;
    longitude: number;
    shortwaveRadiation: number;
    solarCapacity: number;
    timestamp: _Timestamp;
    feasibilityStatus: _FeasibilityStatus;
    locationName: string;
    predictedDailyOutput: number;
}): {
    id: string;
    cloudCover: number;
    latitude: number;
    predictedWeeklyOutput: number;
    precipitation: number;
    temperature: number;
    azimuthAngle: number;
    predictedYearlyOutput: number;
    predictedMonthlyOutput: number;
    zenithAngle: number;
    humidity: number;
    longitude: number;
    shortwaveRadiation: number;
    solarCapacity: number;
    timestamp: Timestamp;
    feasibilityStatus: FeasibilityStatus;
    locationName: string;
    predictedDailyOutput: number;
} {
    return {
        id: value.id,
        cloudCover: value.cloudCover,
        latitude: value.latitude,
        predictedWeeklyOutput: value.predictedWeeklyOutput,
        precipitation: value.precipitation,
        temperature: value.temperature,
        azimuthAngle: value.azimuthAngle,
        predictedYearlyOutput: value.predictedYearlyOutput,
        predictedMonthlyOutput: value.predictedMonthlyOutput,
        zenithAngle: value.zenithAngle,
        humidity: value.humidity,
        longitude: value.longitude,
        shortwaveRadiation: value.shortwaveRadiation,
        solarCapacity: value.solarCapacity,
        timestamp: value.timestamp,
        feasibilityStatus: from_candid_FeasibilityStatus_n8(_uploadFile, _downloadFile, value.feasibilityStatus),
        locationName: value.locationName,
        predictedDailyOutput: value.predictedDailyOutput
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    good: null;
} | {
    poor: null;
} | {
    moderate: null;
} | {
    excellent: null;
}): FeasibilityStatus {
    return "good" in value ? FeasibilityStatus.good : "poor" in value ? FeasibilityStatus.poor : "moderate" in value ? FeasibilityStatus.moderate : "excellent" in value ? FeasibilityStatus.excellent : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Record>): Array<Record_> {
    return value.map((x)=>from_candid_Record_n6(_uploadFile, _downloadFile, x));
}
function to_candid_CreatePredictionRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreatePredictionRequest): _CreatePredictionRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_FeasibilityStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeasibilityStatus): _FeasibilityStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cloudCover: number;
    latitude: number;
    predictedWeeklyOutput: number;
    precipitation: number;
    temperature: number;
    azimuthAngle: number;
    predictedYearlyOutput: number;
    predictedMonthlyOutput: number;
    zenithAngle: number;
    humidity: number;
    longitude: number;
    shortwaveRadiation: number;
    solarCapacity: number;
    feasibilityStatus: FeasibilityStatus;
    locationName: string;
    predictedDailyOutput: number;
}): {
    cloudCover: number;
    latitude: number;
    predictedWeeklyOutput: number;
    precipitation: number;
    temperature: number;
    azimuthAngle: number;
    predictedYearlyOutput: number;
    predictedMonthlyOutput: number;
    zenithAngle: number;
    humidity: number;
    longitude: number;
    shortwaveRadiation: number;
    solarCapacity: number;
    feasibilityStatus: _FeasibilityStatus;
    locationName: string;
    predictedDailyOutput: number;
} {
    return {
        cloudCover: value.cloudCover,
        latitude: value.latitude,
        predictedWeeklyOutput: value.predictedWeeklyOutput,
        precipitation: value.precipitation,
        temperature: value.temperature,
        azimuthAngle: value.azimuthAngle,
        predictedYearlyOutput: value.predictedYearlyOutput,
        predictedMonthlyOutput: value.predictedMonthlyOutput,
        zenithAngle: value.zenithAngle,
        humidity: value.humidity,
        longitude: value.longitude,
        shortwaveRadiation: value.shortwaveRadiation,
        solarCapacity: value.solarCapacity,
        feasibilityStatus: to_candid_FeasibilityStatus_n3(_uploadFile, _downloadFile, value.feasibilityStatus),
        locationName: value.locationName,
        predictedDailyOutput: value.predictedDailyOutput
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeasibilityStatus): {
    good: null;
} | {
    poor: null;
} | {
    moderate: null;
} | {
    excellent: null;
} {
    return value == FeasibilityStatus.good ? {
        good: null
    } : value == FeasibilityStatus.poor ? {
        poor: null
    } : value == FeasibilityStatus.moderate ? {
        moderate: null
    } : value == FeasibilityStatus.excellent ? {
        excellent: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
